yonadev/yona-app-ios

- Yona/Yona/nl.lproj/Localizable.strings
Small fix to dutch translation
> Fix to dutch translation

- Yona/Yona/DataService/APIServiceManager.swift
- Yona/Yona/DataService/Users.swift
- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/KeychainManager.swift
- Yona/Yona/SMSValidation/SMSValidationViewController.swift
- Yona/YonaTests/YonaTests.swift
- Save user details to keychain rather than nuserdefaults
> Save user details to keychain other than to user defaults

- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameNoGoChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/SignUp/SignUpFirstStepViewController.swift
- Yona/Yona/WalkThrough/WalkThroughViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
Delete button only visible when edit link is avialable.
TimeZone description text displays now correctly.
NoGo detail screen image is replaced.
> Timeframe delete when editable link, timezone description text

- Yona/Yona/DashBoard/Dashboard.storyboard
- Yona/Yona/DashBoard/TabBarSegue.swift
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Settings/Settings.storyboard
Finished to setup the tab bar logic, to switch through all the view controller.
> Setup dashboard/tabbar logic

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/Login.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/Passcode/ConfirmPasscode.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/Passcode/Passcode.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/SMSValidation.storyboard
- Yona/Yona/Others/UIColor+YIColors.swift
- Yona/Yona/Profile/Profile.storyboard
- Yona/Yona/Settings/Settings.storyboard
- Yona/Yona/Settings/SettingsViewController.swift
- Nav bar fixed for all the screens
> Nav bar fixed for all the screens

- Yona/Yona/Others/UIColor+YIColors.swift
- Yona/Yona/Settings/Settings.storyboard
- Yona/Yona/Settings/SettingsViewController.swift
- Yona/Yona/SignUp/SignUpSecondStepViewController.swift
- Yona/Yona/StringExtensions.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
Quick fixes, displayed custom alerts on Over-ride user.
> Quick fixes, displayed custom alerts

- Yona/Yona/NewDeviceRequestManager.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/SMSValidationViewController.swift
- Yona/Yona/Settings/SettingsViewController.swift
SMS validation fix
AlphaNumeric Code
> Alphanumeric add device code

- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/Date.swift
TimePicker value is now roundoff to next 15 minutes interval.
> Time roundoff to 15 minutes is fixed.

- Yona/Yona/Others/AddNewDevice/AddDeviceViewController.storyboard
- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
Check user exists or not, if not then redirect to welcome screen.
> User exist check on login

- Yona/Yona/Challenges/TimeBucketChallenges.swift
Sorted activity array and goals array
> Sorted activity array and goals array

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
blocked user now will not be able to enter passcode
> blocked user now will not be able to enter passcode

- Yona/Yona.xcodeproj/project.pbxproj
> removed debug flags

- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/LoginSignupValidationMasterView.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
Pin reset button is now visible all the time
> Pin reset button will now be diaplayed from the very first attempt

- Yona/Yona/AcitivitiesRequestManager.swift
- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Manager.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/LoginSignupValidationMasterView.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/SMSValidationViewController.swift
- Yona/Yona/SignUp/SignUpSecondStepViewController.swift
- Message removed PIN reset
- Blocked app when press pin reset
> - API Goals calls reduced to 1

- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
Updated localization message for Unsubscription.
> Updated localization message and remove older message

- Yona/Yona/Others/Constants.swift
- Yona/Yona/SignUp/SignUpSecondStepViewController.swift
check buddy exists for override
> check buddy exists for override

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/AppDelegate.swift
- Yona/Yona/BaseViewController.swift
- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/DashBoard/BaseTabViewController.swift
- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/Friends/FriendsOverViewViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/Profile/ProfileViewController.swift
- Yona/Yona/Settings/SettingsViewController.swift
Implemented the logic to display the current screen after login when App comes to foreground.
created a base class for managing the tabs and the screens.
> Updated login screen logic when came to foreground

- Yona/R.generated.swift
- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Settings/Privacy.storyboard
- Yona/Yona/Settings/PrivacyStatementVC.swift
- Yona/Yona/Settings/Settings.storyboard
- Yona/Yona/Settings/SettingsViewController.swift
Privacy - Header and Footer are missing on Privacy page - Fixed
Privacy - Application UI breaks if user opens the Privacy page, minimize the app and restore it. - Fixed
> Added privacy header footer and fixed ui break issue

- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
- Budget goals were not updated - Fixed
- Picker shows up in time bucket screen - Fixed
- Updated localization text.
> Quick fixes for challenges screens

- Yona/Yona/AppDelegate.swift
- Yona/Yona/BaseViewController.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameNoGoChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/DashBoard/BaseTabViewController.swift
- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/Settings/SettingsViewController.swift
-  Handeled viewcontroller notification observer
- Created flag to manage the base tab to get display
> Updated default tabbar logic

- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameNoGoChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/Others/KeyboardProtocol.swift
- Yona/Yona/WalkThrough/WalkThroughViewController.swift
> Removed strong reference

- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
UI freezes when user deletes budget goals - Fixed
Removed unwanted code.
> UI freezes when user deletes budget goals, removed unwanted code

- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
default duration for adding budget goals - fixed
> default duration for adding budget goals - fixed

- Yona/Yona/Array.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
Date picker in timezone freezes UI fixed
> Date picker in timezone issue fixed

- Yona/Yona/Others/SMSValidPasscodeLogin/LoginSignupValidationMasterView.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/SMSValidationViewController.swift
- Hide loading wheel on sms validation (looks like it is hanging)
- Crash in pin reset (unwrap optional)
> Pin reset, loading wheel sms

- Yona/Yona/Others/SMSValidPasscodeLogin/LoginSignupValidationMasterView.swift
- Yona/Yona/StringExtensions.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
iSO date time parse for Pin reset
> iSO date time parse for Pin reset

- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/LoginSignupValidationMasterView.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Passcode/ConfirmPasscodeViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/SMSValidationViewController.swift
- Yona/Yona/StringExtensions.swift
Message showing time left before you get pin reset code
> Show clear pin message when time left

- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
On delete refreshing table data.
> refreshing table data after delete.

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/DashBoard/Dashboard.storyboard
- Yona/Yona/Settings/PrivacyStatementVC.swift
- Yona/Yona/Settings/Settings.storyboard
- Yona/Yona/Settings/SettingsViewController.swift
> Settings nav bar updated

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Friends/FriendsOverViewViewController.swift
- Yona/Yona/FriendsProfileMasterView.swift
- Yona/Yona/Notifications/ProfileViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> get all REQUESTED buddies

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Others/CustomPicker/YonaCustomDatePickerView.xib
Fixes the updating and saving of the picker issue and interval set to 15 minutes
> APPDEV-422 and 420 Changed interval of time picker

- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameNoGoChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/Goal.swift
- Yona/Yona/GoalsRequestManager.swift
- Yona/Yona/Others/Constants.swift
Fixing display issues for iPhone4 & iPhone5 in challenges
Fixing issue with extra entry after update
> Fixing layout issues in Challenges

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Buddies.swift
- Yona/Yona/CustomCells/YonaUserDisplayTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserDisplayTableViewCell.xib
- Yona/Yona/CustomSubclasses/VSTextField.swift
- Yona/Yona/DataService/Users.swift
- Yona/Yona/MeDashBoard/YonaUserProfileViewController.swift
- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/Login.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/ConfirmMobileValidationVC.swift
- Yona/Yona/Welcome/Welcome.storyboard
Handles number change, both succes and error case.   MUST localize the error messages
Handles user profile, change of cell-number, both succes, and number already taken
> Fixed issue where user can enter empty data when editing own user  

- Yona/Yona/VPNFlow/VPNFlow.storyboard
- Yona/Yona/VPNFlow/YonaVPNFlowMainViewController.swift
handling problem, that could result in mobileconfig file not being started first time
> Fixing layout issues, for iPhone 4

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/AcitivitiesRequestManager.swift
- Yona/Yona/Friends/FriendsDayDetailViewController.swift
- Yona/Yona/Friends/FriendsDayViewController.swift
- Yona/Yona/Friends/FriendsWeekDetailWeekController.swift
- Yona/Yona/MeDashBoard/MeDayDetailViewController.swift
> Update to friends day, detail view

- Yona/Yona.xcodeproj/project.pbxproj
Added xaton enterprise provisioning profile
Signed-off-by: Kinnar Vasa <kvasa@mobiquityinc.com>
> Profile update

- Yona/Yona/CustomCells/YonaUserDisplayTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/DAOObjects/WeekSingleActivityGoal.swift
- Yona/Yona/MeDashBoard/MeDayDetailViewController.swift
- Yona/Yona/MeDashBoard/YonaUserProfileViewController.swift
- Yona/Yona/Message.swift
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
- Yona/Yona/Notifications/NotificationsViewController.swift
- Yona/Yona/Others/Enums.swift
- Yona/Yona/UIControlCell/WeekCircleView.swift
- Yona/Yona/UIControlCell/WeekScoreControlCell.swift
- Yona/Yona/UIControlCell/WeekScoreControlCell.xib
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
APPDEV-696
APPDEV-695
APPDEV-693
APPDEV-685
APPDEV-257
APPDEV-752
> bug fixing 

- Yona/R.generated.swift
- Yona/Yona/Buddies.swift
- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeBucketChallenges.swift
- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
APPDEV-756
APPDEV-664
APPDEV-640
> Bug fixing:

- Yona/R.generated.swift
- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/CustomCells/YonaUserDisplayTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/Friends/Cells/TimeLineTimeBucketCell.swift
- Yona/Yona/Friends/Cells/TimeLineTimeZoneCell.swift
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Friends/FriendsDayViewController.swift
- Yona/Yona/Friends/FriendsProfileViewController.swift
- Yona/Yona/Friends/FriendsWeekDetailWeekController.swift
- Yona/Yona/MessageRequestManager.swift
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/Others/Enums.swift
APPDEV-687
APPDEV-747
APPDEV-759
> Further bug fixing

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/BarButtonItemExtensions.swift
- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameNoGoChallengeViewController.swift
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/CustomCells/YonaButtonsTableHeaderView.xib
- Yona/Yona/CustomCells/YonaDefaultTableHeaderView.swift
- Yona/Yona/CustomCells/YonaDefaultTableHeaderView.xib
- Yona/Yona/CustomCells/YonaUserHeaderWithTwoTabTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserHeaderWithTwoTabTableViewCell.xib
- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserTableViewCell.xib
- Yona/Yona/FriendsProfileMasterView.swift
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/UIControlCell/WeekScoreControlCell.xib
- Yona/Yona/Welcome/Welcome.storyboard
APPDEV-757    UI issues with header cell in timeline and me dash board
APPDEV-787    Removed YONA in initial word
APPDEV-752	  Added Gradeint view to Notifications cell
APPDEV-782    removed headers if empty
APPDEV-675    Corrected Colors, Corrected initials
APPDEV-490    Fixed the loader. But there is a problem with the layout and the viewcontrollers
APPDEV-639    Date in header for week view, now uses US-Locale
APPDEV-470    Setting data correct if user clicks on time and not prev / next
APPDEV-796	  Added alertview for the 3 goal types
> APPDEV-785    UI issue with time-zone goal

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/CustomCells/YonaTwoButtonTableViewCell.xib
- Yona/Yona/Friends/FriendsDayViewController.swift
- Yona/Yona/Notifications/NotificationsViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/Login.storyboard
- Yona/Yona/Welcome/Welcome.storyboard
APPDEV-817    Disabled the click in the cell
APPDEV-819    Updated Code for Friends detail
APPDEV-640    Updateing Timezone
APPDEV-780    Fixing text sizes
APPDEV-797	  Fixing save button action
> APPDEV-748    Show nickname instead of firstname

- Yona/R.generated.swift
- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeFrameBudgetChallengeViewController.swift
- Yona/Yona/CustomCells/YonaUserHeaderWithTwoTabTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/DashBoard/BaseTabViewController.swift
- Yona/Yona/DashBoard/Dashboard.storyboard
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
- Yona/Yona/UIControlCell/CommentControlCell.swift
- Yona/Yona/UIControlCell/CommentControlCell.xib
- Yona/Yona/UIControlCell/ReplyToComment.xib
- Yona/Yona/UIControlCell/SendCommentControl.swift
- Yona/Yona/UIControlCell/SendCommentControl.xib
APPDEV-786    Button behavior in TimeBudget Goal
APPDEV-815    Able to send empty comment
APPDEV-789    Spinner implemented
APPDEV-677	  Unable to delete notifications
APPDEV-784    User activity not shown in friends - Not a bug
APPDEV-243    Friend userprofile, wrong colors
> APPDEV-800    Fixed the profile Icon on meDashBoard

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Friends/FriendsProfileViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/Login.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/SMSValidation/PinResetValidationVC.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
APPDEV-824    App Crashes when user clicks on Unfriend Button
APPDEV-783    Tapping and swiping in notifications interfere
> APPDEV-793    Text not proper on pin reset when the timer is on

- Yona/R.generated.swift
- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/AppDelegate.swift
- Yona/Yona/Challenges/Challenges.storyboard
- Yona/Yona/Challenges/TimeFrameTimeZoneChallengeViewController.swift
- Yona/Yona/DAOObjects/TimeLineDayActivityOverview.swift
- Yona/Yona/DashBoard/BaseTabViewController.swift
- Yona/Yona/Friends/Cells/TimeLineNoGoCell.swift
- Yona/Yona/Friends/Cells/TimeLineNoGoCell.xib
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Friends/FriendsProfileViewController.swift
- Yona/Yona/FriendsProfileMasterView.swift
- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
- Yona/Yona/Notifications/NotificationsViewController.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/UIControlCell/WeekScoreControlCell.swift
- Yona/Yona/VPNFlow/YonaVPNFlowMainViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
APPDEV-688    Yona VPN Profile Not Getting Installed
APPDEV-635    VPN not asked to Install again
APPDEV-826    Deleting the Timeframe in timzone goal deletes the timezone challenge
APPDEV-788    Tab bar issue
APPDEV-827    Nav bar issue
APPDEV-830    Keyboard on login screen
APPDEV-832    Device Specific - hard to move the time slider in budget goal
APPDEV-801    When user violates nogo goal, It does not display properly on firends timeline
APPDEV-833    Device Specific - UI not proper on Dashboard
APPDEV-828    UI Issue when user is seeing friend request and friends profile from notification
APPDEV-831    Device Specific - Able to move the screen of application not only up an down, but also left and right a bit
> APPDEV-689    App Crashes when installing VPN profile

- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/UIControlCell/NoGoCell.xib
- Yona/Yona/en.lproj/Localizable.strings
translation and highlight button
> Added highlight background in add friends.

- Yona/Yona/DashBoard/Dashboard.storyboard
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Friends/FriendsDayViewController.swift
- Yona/Yona/FriendsProfileMasterView.swift
- Yona/Yona/MeDashBoard/MeDayDetailViewController.swift
- Yona/Yona/MeDashBoard/MeWeekDetailWeekViewController.swift
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/UIControlCell/CommentControlCell.xib
- Yona/Yona/UIControlCell/CommentTableHeader.xib
- Yona/Yona/UIControlCell/ReplyToComment.xib
- Yona/Yona/UIControlCell/SendCommentControl.swift
- Yona/Yona/UIControlCell/SendCommentControl.xib
- Yona/Yona/Welcome/Welcome.storyboard
Made sure comment control delegate was set!
> Fixed the dismiss of the comment control

- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/Login.storyboard
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/Settings/SettingsViewController.swift
Settings page UI changes, fixes to the change pin function from this page
> settings page

- Yona/Yona/Welcome/Welcome.storyboard
> [APPDEV-957] Support for Multi line label on login Screen

- Yona/Yona/CustomCells/YonaUserTableViewCell.xib
> [APPDEV-979] - UI issue on Friends View

- Yona/Yona/Others/UIColor+YIColors.swift
> [APPDEV-969] - Change Color unread notifications

- Yona/Yona/Settings/Settings.storyboard
- Yona/Yona/Settings/SettingsViewController.swift
> [APPDEV-974] - Change PIN code - Remove this from settings

- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/Others/AddNewDevice/AddDeviceViewController.swift
- Yona/Yona/Others/Constants.swift
- Yona/Yona/SignUp/SignUpSecondStepViewController.swift
> [APPDEV-956] Country prefix editable for phone numbers

- Yona/Yona/Settings/Settings.storyboard
- Yona/Yona/Settings/SettingsViewController.swift
Reverts yonadev/yona-app-ios#257
> Revert "[APPDEV-974] - Change PIN code - Remove this from settings"

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
> [APPDEV-988] Remove option to Reset Pin from Pin screens

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
> [APPDEV-988] Set pin total attempt to 3 from 5

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
> [APPDEV-987] - It takes 3-5 seconds before I can enter the pin on launch of the app

- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-977] - Labels on NoGo Goal settings screen

- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-975] - Headers not consistent in Uppercase

- Yona/Yona/Friends/Cells/TimeLineHeaderCell.swift
- Yona/Yona/Friends/Cells/TimeLineHeaderCell.xib
> [APPDEV-976] - Label issue in Friends Overview

- Yona/Yona/CustomCells/YonaUserTableViewCell.xib
Reverts yonadev/yona-app-ios#255
> Revert "[APPDEV-979] - UI issue on Friends View"

- Yona/Yona/FriendsProfileMasterView.swift
- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
> [APPDEV-986] - performance Yona app on iOS

- Yona/Yona/AppDelegate.swift
> [APPDEV-997] - Labels appearing on back button

- Yona/Yona/nl.lproj/Localizable.strings
> add login string

- Yona/Yona/Others/UIColor+YIColors.swift
> Develop -> QA

- Yona/Yona/Friends/FriendsDayViewController.swift
> [APPDEV-978] - Friends Day view not correct

- Yona/Yona/DataService/APIServiceManager.swift
- Yona/Yona/UserRequestManager.swift
> [APPDEV-944] - Password generation at Server - iOS

- Yona/Yona/Settings/SettingsViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-931] - New settings menu point - contact support

- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/UserRequestManager.swift
> [APPDEV-965] - Inform server when app is opened

- Yona/Yona/Buddies.swift
- Yona/Yona/BuddyRequestManager.swift
- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/Message.swift
- Yona/Yona/Others/Enums.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
As per lastMonitoredActivityDate key in the buddy API
> [APPDEV-967] Implemented Last seen date of the buddy

- Yona/Yona/AppDelegate.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
> [APPDEV-960] - VPN is not running message does not show up on fresh app start

- Yona/Yona/UIControlCell/TimeZoneCustomView.swift
> [APPDEV-968] - UI Issue Time Zone Bar

- Yona/Yona/VPNFlow/YonaVPNFlowMainViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-945] - Take user to OpenVPN during onboarding

- Yona/R.generated.swift
- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/Message.swift
- Yona/Yona/MessageRequestManager.swift
- Yona/Yona/Notifications/MeDashBoard.storyboard
- Yona/Yona/Notifications/NotificationDetailViewController.swift
- Yona/Yona/Notifications/NotificationsViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
Also prevented unsupported message to be displayed in Notifications
> [APPDEV-961] Added support to system messages

- Yona/Yona/Settings/SettingsViewController.swift
> [APPDEV-959] - VPN Issues - reregister as a user

- Yona/Yona/AppDelegate.swift
- Yona/Yona/Settings/SettingsViewController.swift
> [APPDEV-945] - Was issue in Unscubscribe and resubscribe

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
> [APPDEV-972] - Show pop up for touch id before tapping on icon

- Yona/Yona/DataService/Users.swift
> [APPDEV-1016] - When you request a device code, and log in with it, the app does not work

- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-982] - Capital in Notification detail on No-Go

- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
> [APPDEV-969] - Color unread notifications

- Yona/Yona/UIControlCell/CommentControlCell.swift
> [APPDEV-970] - Avatar Colors

- Yona/Yona/Notifications/NotificationsViewController.swift
> [APPDEV-995] - Delete notification issue

- Yona/Yona/CommentRequestManager.swift
- Yona/Yona/MessageRequestManager.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-920] - Error on delete of notification

- Yona/Yona/Settings/SettingsViewController.swift
- Yona/Yona/Welcome/WelcomeViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-994] - Internet connection broken after 'Uitschrijven'

- Yona/Yona/AcitivitiesRequestManager.swift
- Yona/Yona/Message.swift
- Yona/Yona/Others/Enums.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-1021] - Challenge modified message

- Yona/Yona/en.lproj/Localizable.strings
> [APPDEV-1021] - Update localized text

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/AppDelegate.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/Reachability.swift
> [APPDEV-1017] - strange error when internet is offline

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/UIControlCell/DayViewLinkCell.xib
> [APPDEV-949] - length of url on NoGo notification view

- Yona/Yona/Friends/FriendsDayDetailViewController.swift
> [APPDEV-1019] - Disappearing chat text bar - still presented.

- Yona/Yona/Notifications/NotificationsViewController.swift
> [APPDEV-966] - Notification screen limited to 20 messages

- Yona/Yona/MeDashBoard/MeDayDetailViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
> [APPDEV-983] - NoGo Notification Friend - Missing sections

- Yona/Yona/UIControlCell/SendCommentControl.swift
> Message was sending multiple times if clicked more times

- Yona/Yona/DataService/Users.swift
- Yona/Yona/Others/Constants.swift
- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Yona/Yona/UserRequestManager.swift
- Updated link yona:postOpenAppEvent fromUser entity.
- Posting app version from app metadata
> APPDEV-1106 iOS app does not send "OpenApp" event

- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
- Yona/Yona/Others/Constants.swift
- Resize the profile image to fit into the give size
- Added generic resize method.
> APPDEV-1141 Profile picture is not displayed properly in Dashboard

- .gitignore
- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Buddies.swift
- Yona/Yona/CustomCells/YonaUserDisplayTableViewCell.swift
- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/MeDashBoard/YonaUserProfileViewController.swift
- Yona/Yona/Others/AddNewDevice/AddDeviceViewController.swift
- Yona/Yona/Others/Constants.swift
- Yona/Yona/SignUp/SignUpSecondStepViewController.swift
- Yona/Yona/StringExtensions.swift
- Yona/Yona/en.lproj/Localizable.strings
- Yona/Yona/nl.lproj/Localizable.strings
- Yona/YonaTests/MobileNumberValidationTests.swift
- Removed code which replace mobile num "310" with "+31"
- Also removed extra empty lines and dead code
> APPDEV-1131 Extra (+) symbol added in mobile number in alert pop up.

- Yona/Yona/StringExtensions.swift
- Yona/YonaTests/MobileNumberValidationTests.swift
This is a suggestion. I personally feel the tests are more readable when then inputs and expected result are close to each other.
If you like it, approve it and merge it. If you don't like it, just close this PR.
> APPDEV-1148 Enhance unit test readability

- Jenkinsfile
- Added slack channel warning message for user interaction where pipeline needs input.
1. To enter Release notes before building the app.
> APPDEV-1173 Add slack messages for waiting user input in pipeline

- Yona/Yona/DaySingleActivityDetail.swift
- Removed check of user goal link and different types of goals link
- Code refactored
> APPDEV-1176 Open No Go alert of buddy getting no data found error

- Yona/Yona/Info.plist
APPDEV-1195 Add faceID usage permission
- Added faceID usage permission
APPDEV-1180 Add photo library usage permission for iOS 11 and later
- Added photo library usage permission
- Also updated existing permission string value
> APPDEV-1195 Add faceID usage permission

- Yona/Yona/MeDashBoard/YonaUserProfileViewController.swift
- Fixed navigation title color to white
- Code refactored
> APPDEV-1190 Navigation title color changed after profile picture update

- Yona/Yona/Others/SMSValidPasscodeLogin/Login/LoginViewController.swift
- Refactored code to avoid extra pin validation call
> APPDEV-1199 Two times making getUser request call on pin code validation screen

- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/Message.swift
- Yona/Yona/Others/Enums.swift
- Show adult-sad image if message type: GoalConflictMessage.
- Display user photo if added by user.
- Code refactored
> APPDEV-1198 Display user pic and smiley(for GoalConflictMessage) in notification list

- Yona/Yona/Message.swift
- Yona/Yona/Notifications/NotificationsViewController.swift
- Implemented navigation to friend profile for message type "BuddyInfoChangeMessage"
- Removed extra whitespaces and clean code
> APPDEV-1192 Navigate to friend profile for notification type BuddyInfoChangeMessage

- Yona/Yona.xcodeproj/project.pbxproj
- Yona/Yona/Date.swift
- Yona/Yona/Friends/Friends.storyboard
- Yona/Yona/Friends/FriendsDashBoardViewController.swift
- Yona/Yona/Friends/FriendsDashboardViewController.swift
- Yona/Yona/FriendsProfileMasterView.swift
- Yona/Yona/Notifications/MeDashBoardMainViewController.swift
- Load next 3 days/week data after scroll
- Rename one class name
- Removed blank lines and dead code
APPDEV-1217 Fix for me-dashboard week date header issue
- Corrected code to get date data
- Updated timezone to UTC
> APPDEV-1229 Fix for scroll issue in friend dashboard

- Yona/Yona/DataService/APIServiceManager.swift
- Yona/Yona/Manager.swift
- Yona/Yona/Others/Enums.swift
- Yona/Yona/RequestResult.swift
- Updated code to accept 2xx status codes as success
- Code refactor
> APPDEV-1112 Accept 2xx status codes, not just 200 

- Yona/Yona/AcitivitiesRequestManager.swift
- Yona/Yona/Buddies.swift
- Yona/Yona/GoalsRequestManager.swift
- Parsing buddy goal link(yona:goals) from get buddies request
- Minor code refactor
> APPDEV-1243 Buddy get all goals link issue

- Yona/Podfile
- Yona/Podfile.lock
- Yona/Pods/Manifest.lock
- Yona/Pods/Pods.xcodeproj/project.pbxproj
- Yona/Yona/AcitivitiesRequestManager.swift
- Yona/Yona/Buddies.swift
- Yona/Yona/GoalsRequestManager.swift
- All pods updated to latest version and pod version maintained in Podfile.lock file
> APPDEV-1243 Pod libraries update

- Yona/Yona/Buddies.swift
- Parsing Buddy goals and nickname from user entity embedded in the buddy entity
- Added code for parsing buddy photo URL
- Removed extra lines
> APPDEV-1107 Take goals and nickname from the embedded user entity rather than the buddy entity

- Yona/Yona/CustomCells/YonaUserHeaderWithTwoTabTableViewCell.swift
- Yona/Yona/CustomCells/YonaUserHeaderWithTwoTabTableViewCell.xib
- Yona/Yona/Friends/FriendsDashboardViewController.swift
- Yona/Yona/MeDashBoard/YonaUserProfileViewController.swift
- Code updated to show buddy first name and last name in header
- Profile icon of dashboard, display buddy pic if uploaded, otherwise first letter of nick name
- Handled buddy pic inside friend profile view
- Code refactor
> APPDEV-1246 Friends dashboard navigation title header issue

- Yona/Yona/UserRequestManager.swift
- Added null check for user self link, if nil, returning stored url from keychain.
> APPDEV-1261 iOS app crash while add device

- Yona/Yona/CustomCells/YonaUserTableViewCell.swift
- Yona/Yona/Friends/AddFriendsViewController.swift
- Yona/Yona/en.lproj/Localizable.strings
APPDEV-1257 Fixed Localization issue
-Updated English Localizable.string file for accept friend request
APPDEV-1258 Fixed loader issue
APPDEV-1262 Fixed notification sad emoji overlapping issue
> APPDEV-1257 Accept buddy request screen localization issue
